version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - db:/var/lib/mysql
      - ./sqls/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  web:
    build: ./web
    image: web:24
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    links:
      - mysql:db
volumes:
  db: